### PR TITLE
feat(preferences): Create preference for opting in/out of showing war…

### PR DESCRIPTION
**Pull request by mleeBoeing**
Create preference for opting in/out of showing the leaving ozp modal

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by skhtet** [comment]
:+1:

**Comment by rkenyon1969** [comment]
@mleeBoeing - per our conversation, please don't merge until you've reviewed changing default from False to True:

**ozpcenter/models.py:**
`743     leaving_ozp_warning_flag = models.BooleanField(default=True)`

and tested.

thxs.,

**Comment by mleeBoeing** [comment]
Updated

**Comment by blynch11p** [comment]
👍

**Pull request merged**
