### PR TITLE
feat(listing): Added Route and Template for Similar Listings

### PR DESCRIPTION
**Pull request by mannyrivera2010**
````
GET /api/listing/1/similar/
Host: 127.0.0.1:8001
Authorization: Basic YmlnYnJvdGhlcjpwYXNzd29yZA==
Content-Type: application/json
Respond:
[
  {
      Listing Serializer JSON....
  },
  { ....
  }
]
````
TODO:
Figure out the Similar Listing Algorithm

### CODE REVIEW

**Comment by akonsowski** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
Please Review:
@seenusuvarna 
@akonsowski 
@lsemesky

**Comment by mannyrivera2010** [comment]
To test: http://127.0.0.1:8001/api/listing/1/similar/

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
