### PR TITLE
fix(library): Shared Bookmark

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review:
@akonsowski 
@lsemesky 
@J-Fid 
@seenusuvarna

### CODE REVIEW

**Comment by lsemesky** [comment]
http://localhost:8088/dist/#/add/New Folder1nn22nn/"[{\"id\":13},{\"id\":11},{\"id\":103}]"

**Comment by mannyrivera2010** [comment]
Private Apps Are Showing, Should not be visible

**Comment by mannyrivera2010** [comment]
The way it currently works,  
For **http://localhost:8088/dist/#/add/New%20Folder1/1,2** Request, it will will do 3 request.  

One post for each listing that needs to be created
````
Request URL:http://127.0.0.1:8001/api/self/library/
Request Method:POST
Status Code:201 CREATED
Remote Address:127.0.0.1:8001
Payload:
{"listing":{"id":2}}
````

One Update all,
````
Request URL:http://127.0.0.1:8001/api/self/library/update_all/
Request Method:PUT
Status Code:200 OK
Payload:
[{"listing":{"id":1},"folder":"New Folder1","id":11,"position":0},
{"listing":{"id":2},"folder":"New Folder1","id":12,"position":1}]
````

**Comment by mannyrivera2010** [comment]
I propose a new endpoint that will batch the creation.

For http://localhost:8088/dist/#/add/New%20Folder1/1,2 Request, it will will do 3 request.
````
Request URL:http://127.0.0.1:8001/api/self/library/create_all/
Request Method:PUT
Status Code:200 OK
Payload:
[{"listing":{"id":1},"folder":"New Folder1","position":0},
{"listing":{"id":2},"folder":"New Folder1","position":1}]
````

**Comment by lsemesky** [comment]
Here's some thoughts if we care about implementing REST properly: http://restlet.com/blog/2015/05/18/implementing-bulk-updates-within-restful-services/

**Comment by mannyrivera2010** [comment]
Good Points of implementing REST

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
