### PR TITLE
refactor(tests): refactor Test and add postgresql tests

### PR DESCRIPTION
**Pull request by mannyrivera2010**
**Purpose**    
- Refactor unit tests and add postgresql tests. 
- Add Postgresql to run on travis ci
 
Assumes that postgresql is already installed on the machine 

To setup up postgresql: 
```
sudo su postgres
psql -c "CREATE USER ozp_usera WITH PASSWORD 'password';" 
psql -c 'ALTER USER ozp_user CREATEDB;' 
psql -c 'CREATE DATABASE ozp;' 
psql -c 'GRANT ALL PRIVILEGES ON DATABASE ozp TO ozp_user;' 
```

To Test Locally run the following commands 
```shell
# to test postgres
make ptest_psql

# to test sqlite
make ptest
```

**Please Review**    
@aml-development/ozp-backend-team  

**Checklist**    
- [x] Add unit tests for code    
- [x] Code is PEP8 Compliant   
- [x] 2 people reviewed code

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
Fixed Similar DB Issue:
Exception Value: more than one row returnd by a subquery used as an
expression
```
SELECT DISTINCT "ozpcenter_listing"."id", "ozpcenter_listing"."title", "ozpcenter_listing"."approved_date", "ozpcenter_listing"."edited_date",
 "ozpcenter_listing"."agency_id", "ozpcenter_listing"."listing_type_id", "ozpcenter_listing"."description", "ozpcenter_listing"."launch_url", 
"ozpcenter_listing"."version_name", "ozpcenter_listing"."unique_name", "ozpcenter_listing"."small_icon_id", "ozpcenter_listing"."large_icon_id", 
"ozpcenter_listing"."banner_icon_id", "ozpcenter_listing"."large_banner_icon_id", "ozpcenter_listing"."what_is_new", "ozpcenter_listing"."description_short", 
"ozpcenter_listing"."usage_requirements", "ozpcenter_listing"."system_requirements", "ozpcenter_listing"."approval_status", "ozpcenter_listing"."is_enabled", 
"ozpcenter_listing"."is_featured", "ozpcenter_listing"."is_deleted", "ozpcenter_listing"."avg_rate", "ozpcenter_listing"."total_votes", "ozpcenter_listing"."total_rate5", 
"ozpcenter_listing"."total_rate4", "ozpcenter_listing"."total_rate3", "ozpcenter_listing"."total_rate2", "ozpcenter_listing"."total_rate1", "ozpcenter_listing"."total_reviews", 
"ozpcenter_listing"."total_review_responses", "ozpcenter_listing"."feedback_score", "ozpcenter_listing"."iframe_compatible", "ozpcenter_listing"."required_listings_id", 
"ozpcenter_listing"."last_activity_id", "ozpcenter_listing"."current_rejection_id", "ozpcenter_listing"."security_marking", "ozpcenter_listing"."is_private" 
FROM "ozpcenter_listing" INNER JOIN "category_listing" ON ("ozpcenter_listing"."id" = "category_listing"."listing_id") 
WHERE ("ozpcenter_listing"."approval_status" = 'APPROVED' 
AND "category_listing"."category_id" = (SELECT U0."id" AS Col1 FROM "ozpcenter_category" U0 INNER JOIN "category_listing" U1 ON (U0."id" = U1."category_id") WHERE U1."listing_id" = 2));
```
to 
```
SELECT DISTINCT "ozpcenter_listing"."id", "ozpcenter_listing"."title", "ozpcenter_listing"."approved_date", "ozpcenter_listing"."edited_date",
 "ozpcenter_listing"."agency_id", "ozpcenter_listing"."listing_type_id", "ozpcenter_listing"."description", "ozpcenter_listing"."launch_url", 
"ozpcenter_listing"."version_name", "ozpcenter_listing"."unique_name", "ozpcenter_listing"."small_icon_id", "ozpcenter_listing"."large_icon_id", 
"ozpcenter_listing"."banner_icon_id", "ozpcenter_listing"."large_banner_icon_id", "ozpcenter_listing"."what_is_new", "ozpcenter_listing"."description_short", 
"ozpcenter_listing"."usage_requirements", "ozpcenter_listing"."system_requirements", "ozpcenter_listing"."approval_status", "ozpcenter_listing"."is_enabled", 
"ozpcenter_listing"."is_featured", "ozpcenter_listing"."is_deleted", "ozpcenter_listing"."avg_rate", "ozpcenter_listing"."total_votes", "ozpcenter_listing"."total_rate5", 
"ozpcenter_listing"."total_rate4", "ozpcenter_listing"."total_rate3", "ozpcenter_listing"."total_rate2", "ozpcenter_listing"."total_rate1", "ozpcenter_listing"."total_reviews", 
"ozpcenter_listing"."total_review_responses", "ozpcenter_listing"."feedback_score", "ozpcenter_listing"."iframe_compatible", "ozpcenter_listing"."required_listings_id", 
"ozpcenter_listing"."last_activity_id", "ozpcenter_listing"."current_rejection_id", "ozpcenter_listing"."security_marking", "ozpcenter_listing"."is_private" 
FROM "ozpcenter_listing" INNER JOIN "category_listing" ON ("ozpcenter_listing"."id" = "category_listing"."listing_id") 
WHERE ("ozpcenter_listing"."approval_status" = 'APPROVED' 
AND "category_listing"."category_id" IN (SELECT U0."id" AS Col1 FROM "ozpcenter_category" U0 INNER JOIN "category_listing" U1 ON (U0."id" = U1."category_id") WHERE U1."listing_id" = 2));
```

**Comment by skhtet** [comment]
:+1:

**Comment by cwilliams2017** [comment]
:+1:

**Comment by lsemesky** [comment]
:+1:

**Pull request merged**
