### PR TITLE
fix(profile): Corrected Profiles Listing Endpoint

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@seenusuvarna 
@J-Fid 
@skhtet 
@mleeBoeing 

Jira Ticket: 625

### CODE REVIEW

**Comment by lsemesky** [comment]
Blocked by @skhtet

**Comment by skhtet** [comment]
I could not find the Jira ticket corresponding to this PR. But this looks like the fix to address owned listings not showing up on profile modals, correct?

**Comment by mleeBoeing** [comment]
Ticket is 625 in JIRA

**Comment by skhtet** [comment]
Found it in the backlog, will open it up and we can get this in for the next build.

**Comment by skhtet** [comment]
:+1:

**Comment by skhtet** [comment]
@mleeBoeing pls review

**Comment by mleeBoeing** [comment]
:+1:

**Pull request merged**
