### PR TITLE
feat(es): upgrade to elasticsearch 6.3

### PR DESCRIPTION
**Pull request by mannyrivera2010**
AMLOS-399
AMLOS-462

**Description**     
Document how upgrading to Elasticsearch 6.x will impact code changes needed
Upgrade to Elasticsearch 6.3.2

**Acceptance Criteria**   
Code base has been upgraded to use Elasticsearch 6.3.2
 
**How to test code**    
Download Elasticsearch
```
ES_VERSION=6.3.2 
ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz
wget ${ES_DOWNLOAD_URL}
tar -xzf elasticsearch-${ES_VERSION}.tar.gz
./elasticsearch-${ES_VERSION}/bin/elasticsearch
```
Create a new python environment
```
rm -rf env
make pyenv
source env/bin/activate
```
Run Unit test and run server 
```
make test_parallel
make dev reindex_es
make run
```
Run Curl Command to test search
```
curl -X GET \
  'http://127.0.0.1:8001/api/listings/essearch/?search=demo_tag&type=Web%20Application' \
  -H 'authorization: Basic YmlnYnJvdGhlcjpwYXNzd29yZA==' \
```
Optional Step: Under `settings.py` change ES_HOST to correct port number. If Elasticsearch 2.3 is also running then port for Elasticsearch 6.3 will be 9201
```
ES_HOST = [{
    "host": "localhost",
    "port": 9200
}]
```

**Please Review**     
@aml-development/ozp-backend-team    

**Checklist**
- [x] Read CONTRIBUTING.md
- [x] Write code to complete task 
- [x] Python Code is PEP8 Compliant
- [x] Add unit tests for new code
- [x] All tests must pass before merging the pull request
- [ ] At least 2 people reviewed code

### CODE REVIEW

**Comment by mleeBoeing** [comment]
Tests are failing for me

**Comment by mannyrivera2010** [comment]
Updated `How to test` section to provide more instructions

**Comment by mleeBoeing** [comment]
:+1:
Tests pass. I was using the old ES.

**Comment by irtiza-rizvi** [comment]
Tests pass, recommended listings load accurately :+1:

**Pull request merged**
