### PR TITLE
updating the peer object serialization so it is not serialized into a…

### PR DESCRIPTION
**Pull request by lsemesky**
… string instead of being kept as an object

to test call http://localhost:8001/api/self/notification/ and ensure the peer field is an object and not a string

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by rkenyon1969** [comment]
- pulled branch
- reviewed code
- tested

:+1:

**Comment by rkenyon1969** [comment]
There is a bug and I'm working with Tiff to test. It is not related to this change.

**Comment by rkenyon1969** [comment]
Tiff reminded me Laura is already working on the above bug:

https://jira.di2e.net/browse/AMLNG-658

**Pull request merged**
