### PR TITLE
ES Content Based Review

### PR DESCRIPTION
**Pull request by seenusuvarna**
Please review:
@mannyrivera2010 
@skhtet 
@blynch11p 
@mleeBoeing 
@rkenyon1969 
@lsemesky 

**To verify do the following:**
(edit ozpcenter/recommend/recommend.py: change line 743 recommendation_weight = 25.0 to recommendation_weight = 1.0)  This is to have the results not show up at the top of the list just as a preventative measure.
>> make recommend_es_user
>> make recommend_es_content
The content based recommendation system uses data from the user based recommendation system so that it is more efficient in using the tables.  That is the reason that the code was modified for user based as well, but mostly was related to the field structure.  There is one section of code that may be removed and has been commented as such since there was a revelation.

**In order to test:**
Use bettafish user (This also assumes that nothing has been bookmarked)
Initial recommended items can be seen at:
http://localhost:8001/api/storefront/
Look for "_score" to see the values that are being recommended  (The listings will be based on what other users have bookmarked and what is appearing in the aggregations of the text - This is temporary until we get live recommendations implemented)
Can also load storefront to view the data on the screen.
Then bookmark JotSpot 4 App
rerun make recommend_es_user and followed by make recommend_es_content
After loading the backend again, should see all of the JotSpot apps because of content matching.  The scores should be very high for them as well.

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
:+1:  Syntax look good

**Comment by seenusuvarna** [comment]
Cleaned up some code that was not being used and corrected a comment.  No functionality change.

**Comment by seenusuvarna** [comment]
Merged from Master to es_recommend_content branch so that latest center and back-end code will play will with each other and reduce the amount of work needed by reviewer to verify changes.

**Comment by blynch11p** [comment]
Code looks clean and syntactically correct.
Followed the instructions above to test from Center. 
- Bookmark JotSpot 4, make recommend_es_user and make recommend_es_content, refresh page

The additional JotSpot apps appeared in my Recommended list.

I also bookmarked Air Mail and Skybox 7 and reran the commands and see a spattering of Air Mails and Skyboxes to go along with the JotSpots.

:+1:

**Comment by mannyrivera2010** [comment]
:+1:

**Pull request merged**
