### PR TITLE
Elasticsearch Recommender Engine Optimization

### PR DESCRIPTION
**Pull request by seenusuvarna**
Please review the code that optimizes the code for calculating the recommendations for users.  It reduces the Content results to 20 so that processing will be quicker with all of the text in the new apps.  It removes more code and comments than is added.  It makes the code easier to maintain.  This is very similar to the code from PR #344 (Closing PR and will refer to this one) but the code has been combined into the same recommend.py file and uses methods that were implemented to create the solution, but the engines themselves are very similar.  Performance improvement is a major feature of the code changes.

Please review:
@mannyrivera2010 
@skhtet 
@blynch11p 
@rkenyon1969 

For testing purposes suggest changing the WAIT_TIME to 1 like was reverted in last commit for testing.  The reason for this is because the data is created for both Elasticsearch Recommendation Algorithms at the same time to make it more efficient and create a common place for the documents.
Use API:  <host>:8001/api/storefront/ and search for "_score:" to see results from Ratings

Use bettafish as the user
>> make dev
>> make reindex_es
>> make recommend_es (will run all of the recommendation engines)
(To run just elasticsearch ones: make recommend_es_content and make recommend_es_user are the ones to use)
>> make run_es (to run backend)

Using GUI with bettafish user should see recommendations similar to:
Saturn
Iron Man
Wolf Finder
Satellite navigation*
BeiDou Navigation*
Sun*
Jean Grey*
Air Mail*
Bread Basket*
Acoustic Guitar*
(Ones with * may not be in the same order or may not appear based on other factors)

Using API:
should see Saturn matching all recommendation engines using API
Iron Man should match Baseline, Elasticsearch User Based Filtering and Bookmark Collection Filtering
Wolf Finder should match Baseline and Elasticsearch User Based Filtering
Others may appear after this
Satellite navigation should match Elasticsearch Content Filtering and Elasticsearch User Based Filtering

DO THE FOLLOWING:
Bookmark: Sun and Rate 4 Stars
Bookmark: Satellite navigation and Rate 5 Stars

Then Stop Backend and make sure that time between last time recommend_es or other recommender  executions is greater than WAIT_TIME.
Next run should see:
Saturn
Wolf Finder
Stop sign
Chart Course*
BeiDou Navigation*
Jupiter*
Magnetic positon*
Jasoom*
Global Navigation*
Jean Grey*

The API should show that the first three with more than just one recommendation engine and then jittering will cause a mixture after that.

### CODE REVIEW

**Comment by blynch11p** [comment]
I get an error on `make recommend_es`

```
lastupdate = result_us['hits']['hits'][0]['_source']['lastupdated']
IndexError: list index out of range
Makefile:73: recipe for target 'recommend_es' failed
```

**Comment by seenusuvarna** [comment]
@blynch11p I will look into this shortly.  You started with a fresh install correct?  I will make sure that the code is correct on the branch.

**Comment by seenusuvarna** [comment]
Found the issue.  I will correct it and push a new change shortly.

**Comment by blynch11p** [comment]
How 'fresh'?  I pulled the branch, ran make dev, etc.  I even restarted the elasticsearch server.

**Comment by seenusuvarna** [comment]
There is a code change that is needed will update as soon as my test case is done running.  It was a missed scenario.

**Comment by seenusuvarna** [comment]
The latest change should fix the issue for running the first time.  It checks to see if any results are returned and if it is 0 and if so will then set the lastupdate to 0 and allow the run to proceed.
Let me know if there are any other issues.

**Comment by blynch11p** [comment]
Code looks ok
Followed steps and reproduced the same results
:+1:

**Comment by mannyrivera2010** [comment]
:+1:

**Pull request merged**
