### PR TITLE
Elasticsearch User Based Recommendation changes

### PR DESCRIPTION
**Pull request by seenusuvarna**
Please review:
@mannyrivera2010 
@skhtet 
@J-Fid 
@rkenyon1969 
@blynch11p 

The changes are for implementation for the Elasticsearch User Based Recommendation changes.  The changes also include changes from ozpcenter/api/storefront/model_access.py which are being reviewed by another PR #301.  If needed can remove the changes before merging, but needed to see changes in listings.  

**Note**: The bookmarked listings do not get returned after running the make recommend command for Elasticsearch.  A similar feature can be added to all results if this is desired.

To test recommendations:
Download code
(optional) Clear ozpcenter_recommendentry database contents table using approved SQLite browser
Run: ES_ENABLED=True make recommend
(Command will run all recommendation engines.  If only elasticsearch is required, need to modify /ozp_backend/ozpcenter/scripts/recommend.py by removing the baseline and graph_cf engines when ES_ENABLED is True)
The result should show a difference in Recommendation listings.  To compare one can run without Elasticsearch by running:
make recommend
(Without the ES_ENABLED)

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
@seenusuvarna - Fix Syntax after merging master into this branch

**Comment by blynch11p** [comment]
:+1:

**Comment by seenusuvarna** [comment]
Wondered if we could pull out the changes here:
ozpcenter/scripts/recommend.py
Then the code would only modify the database if the **make recommend_es** is run _instead_ of **make recommend** command.  This will allow us to close out the issue and have the code available in the mainline and further development without falling further back from the mainline.

This way we could potentially test how differently the elasticsearch recommendation system is compared to the python based system.
Please comment on this approach?

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by blynch11p** [comment]
:+1:

**Comment by seenusuvarna** [comment]
Changed query to give more accurate results.  Confirmed with @mannyrivera2010  and @blynch11p  that the change was okay and will merge as soon as quality code check is completed.

**Comment by mannyrivera2010** [comment]
:-1:    It seem like the merge from master was done incorrectly

**Comment by seenusuvarna** [comment]
Replacing PR with #314

**Pull request closed without merging**
