### PR TITLE
refactor(documentation): Remove outdated references in documentation

### PR DESCRIPTION
**Pull request by mleeBoeing**
AMLOS-530

**Description**     
Remove outdated references in all of the documentation in current backend repository.

**Acceptance Criteria**   
No text of ozp, ozone, apps mall within documentation. Text should be replaced with generic terms.
 
**How to test code**    
Type mkdocs serve and go to localhost:8000

**Please Review**     
@aml-development/ozp-backend-team    

**Checklist**
- [ ] Read CONTRIBUTING.md
- [ ] Write code to complete task 
- [ ] Python Code is PEP8 Compliant
- [ ] Add unit tests for new code
- [ ] All tests must pass before merging the pull request
- [ ] At least 2 people reviewed code

### CODE REVIEW

**Comment by irizvifearless** [comment]
Rather than changing `ozp` to `aml`, is there any motivation to use a more generic term, like `app`, `core`, `main`, etc?

**Comment by mleeBoeing** [comment]
Decided to use app instead of aml. Changes will be shown in new repository. Keeping this PR open for a little longer for more suggestions.

**Comment by rkenyon1969** [comment]
I suggest AML3.0 repos are generic; documentation not ozp-documentation, ansible not aml-ansible.

Please update documentation to reflect this.

**Comment by mleeBoeing** [comment]
Done. Changes will be shown in new repository.

**Comment by rkenyon1969** [comment]
what about:

screenshot from 2018-02-06 20-30-52

**Comment by mleeBoeing** [comment]
That has been changed locally. You will not see the changes within this pull request as this is in a separate repository now.

**Comment by mannyrivera2010** [comment]
close this?

**Pull request closed without merging**
