### PR TITLE
Fixed Elasticsearch previous/next links

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@lsemesky
@J-Fid
@seenusuvarna
@rkenyon1969
@akonsowski

### CODE REVIEW

**Comment by lsemesky** [comment]
This is for ticket AMLNG-133

**Comment by seenusuvarna** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
@lsemesky - I made the changes

**Comment by seenusuvarna** [comment]
:+1:

**Pull request merged**
