### PR TITLE
refactor(unittest): Increase Performance of unittest

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@lsemesky 
@flesher1 
@mleeBoeing

### CODE REVIEW

**Comment by mleeBoeing** [comment]
:+1:
Time taken before and after:
Around 30 seconds -> around 14 seconds

**Comment by mannyrivera2010** [comment]
On Master Branch
````
make test
-------------------------------------------------------------------------------------------
TOTAL                                                                    7638   2472    68%
----------------------------------------------------------------------
Ran 236 tests in 1320.942s

OK (SKIP=7)
````

**Comment by mleeBoeing** [comment]
:+1:
image
Major improvement

**Comment by rkenyon1969** [comment]
1. pulled branch
2. reviewed code
3. tested

:+1:

**Pull request merged**
