### PR TITLE
feat(feedback): Add Recommendation Feedback

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@mleeBoeing 
@rkenyon1969 
@flesher1 
@skhtet 
@lsemesky 

Create Feedback
```
POST /api/listing/2/feedback/ HTTP/1.1
Host: 127.0.0.1:8001
Authorization: Basic YmlnYnJvdGhlcjpwYXNzd29yZA==

{"feedback":-1}  For Negative Review
{"feedback":1}  For Positive Review
```

`{"feedback":0}`  if user has no feedback on GET request

### CODE REVIEW

**Comment by blynch11p** [comment]
Does this take into consideration both Positive and Negative feedback separately (as described in AMLNG-672)? Or just the overall feedback?

**Comment by mannyrivera2010** [comment]
It will take both in consideration.

**Comment by mleeBoeing** [comment]
:+1:
Able to give negative feedback (-1) to a listing
Able to give positive feedback (+1) to a listing
Able to track if a listing has been given a feedback already by logged in user
Feedback is defaulted to 0

**Comment by mannyrivera2010** [comment]
:+1:  @mleeBoeing  changes are good

**Comment by mleeBoeing** [comment]
Just added fix to is_bookmarked & gave_feedback in listings to be unique to each user

**Comment by mleeBoeing** [comment]
Helpful tests:

- Give negative feedback to listing 5 as bettafish
    - ```curl --request POST --url http://localhost:8001/api/listing/5/feedback/ --header 'authorization: Basic YmV0dGFmaXNoOnBhc3N3b3Jk' --header 'cache-control: no-cache' --header 'content-type: application/json' --data '{"feedback":-1}'```
- Do a GET on listing 5 as bettafish, gave_feedback should equal to true
    - ```curl --request GET --url http://localhost:8001/api/listing/5/ --header 'authorization: Basic YmV0dGFmaXNoOnBhc3N3b3Jk' --header 'cache-control: no-cache'```
- Do a GET on listing 5 as betaraybill, gave_feedback should equal to false since no feedback was given ever
    - ```curl --request GET --url http://localhost:8001/api/listing/5/ --header 'authorization: Basic YmV0YXJheWJpbGw6cGFzc3dvcmQ=' --header 'cache-control: no-cache'```

Test for is_bookmarked field
- Do a POST to bookmark listing 5 as betaraybill
    - ```curl --request POST --url http://localhost:8001/api/self/library/ --header 'authorization: Basic YmV0YXJheWJpbGw6cGFzc3dvcmQ=' --header 'cache-control: no-cache'  --header 'content-type: application/json' --data '{"listing":{"id":5}}'```
- Do a GET on listing 5 as betaraybill, is_bookmarked should equal to true now
    - ```curl --request GET --url http://localhost:8001/api/listing/5/ --header 'authorization: Basic YmV0YXJheWJpbGw6cGFzc3dvcmQ=' --header 'cache-control: no-cache'```
- Do a GET on listing 5 as bettafish, is_bookmarked should equal to false
    - ```curl --request GET --url http://localhost:8001/api/listing/5/ --header 'authorization: Basic YmV0dGFmaXNoOnBhc3N3b3Jk' --header 'cache-control: no-cache'```

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by rkenyon1969** [comment]
Able to give negative feedback (-1) to a listing :white_check_mark:
Able to give positive feedback (+1) to a listing :white_check_mark:
Able to track if a listing has been given a feedback already by logged in user :white_check_mark:

- Give negative feedback to listing 5 as bettafish :white_check_mark:
- Do a GET on listing 5 as bettafish, gave_feedback should equal to true :white_check_mark:
- Do a GET on listing 5 as betaraybill, gave_feedback should equal to false since no feedback was given ever :white_check_mark:
- Do a POST to bookmark listing 5 as betaraybill :white_check_mark:
- Do a GET on listing 5 as betaraybill, is_bookmarked should equal to true now :white_check_mark:
- Do a GET on listing 5 as bettafish, is_bookmarked should equal to false :white_check_mark:

:+1:

**Pull request merged**
